Creating Series

In [5]:
import numpy as np
import pandas as pd

In [6]:
labels = ('a','b','c')
my_list = [10,20,30]
arr = np.array([10,20,30])
d = {1:10,2:20,3:30}
arr
d

{1: 10, 2: 20, 3: 30}

Phele hum list sai series ko create karge

In [7]:
pd.Series(my_list)

0    10
1    20
2    30
dtype: int64

Mujeh custom labels layout krna ha

In [8]:
pd.Series(my_list,index = labels)

a    10
b    20
c    30
dtype: int64

Kya mai ek series ko array sai create kr sakti hu

In [9]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

Kya mai ek series dictionary sai create kr sakti hu

In [10]:
pd.Series(d)

1    10
2    20
3    30
dtype: int64

DataFrame

In [11]:
import numpy as np
import pandas as pd

Creating a dataframe(in dictionary and list)

Yeh Dataframe dictionary ke helps sai create kiya ha

In [12]:
data = {
     'Name': ['Prachi','Rahul','Yash','Mohan'],
      'Age' : [28,34,29,43],
      'City' : ['New york','Paris','Canada','Franch'],
      'Salary' : [65000,70000,62000,85000]
}
df = pd.DataFrame(data)
df

     Name  Age      City  Salary
0  Prachi   28  New york   65000
1   Rahul   34     Paris   70000
2    Yash   29    Canada   62000
3   Mohan   43    Franch   85000

Yeh dataframe list ki helps sai create kiya ha

In [13]:
data_list = [
        ['Prachi', 28 ,'New york', 65000],
        ['Rahul' ,  34 , 'Paris' , 70000],
        ['Yash'  ,   29 , 'Canada',62000],
        ['Mohan' ,  43 , 'Franch', 85000],
]
df2 = pd.DataFrame(data_list)
columns = ['Name','Age','City','Salary']
df2 = pd.DataFrame(data_list,columns = columns)
df2

     Name  Age      City  Salary
0  Prachi   28  New york   65000
1   Rahul   34     Paris   70000
2    Yash   29    Canada   62000
3   Mohan   43    Franch   85000

Selection and Indexing of Columns

phele mujeh sirf ek column ko select krna ha and show krna ha screen per

In [14]:
df2['Name']

0    Prachi
1     Rahul
2      Yash
3     Mohan
Name: Name, dtype: str

ab mujeh one more columns ko select krna ha and show krna ha screen per

In [15]:
df2[["Name","City"]]

     Name      City
0  Prachi  New york
1   Rahul     Paris
2    Yash    Canada
3   Mohan    Franch

Creating a new column

Mujeh df2 mai ek column add krna ha 'Designation' name ka

In [16]:
df2["Designation"] = ["Data Analytic","Doctor","Web developer","Teacher"]
df2

     Name  Age      City  Salary    Designation
0  Prachi   28  New york   65000  Data Analytic
1   Rahul   34     Paris   70000         Doctor
2    Yash   29    Canada   62000  Web developer
3   Mohan   43    Franch   85000        Teacher

Removing Column

Mujeh ab designation column remove krna h but sirf temporary

In [17]:
df2.drop('Designation',axis = 1)

     Name  Age      City  Salary
0  Prachi   28  New york   65000
1   Rahul   34     Paris   70000
2    Yash   29    Canada   62000
3   Mohan   43    Franch   85000

Ab mujeh designation remove krna h but permanent

In [18]:
df2.drop('Designation', axis = 1 , inplace = True)

In [ ]:
df2

Ab mujeh multiple column remove krna ha (City and salary) but temporary

In [ ]:
df2.drop(["City","Salary"],axis = 1)

Ab mujeh 0 wali row ko remove karna h

In [ ]:
df2.drop(0,axis = 0)

Selectiong Rows

Abhi mujeh sirf ek row select krani ha and show bhi krni ha

In [ ]:
df2.loc[0]

Abhi mujeh sirf multiple row select krni h and show bhi krni h

In [ ]:
df2.loc[[0,3]]

Mujeh ab index ke basis per select krni h row

In [ ]:
df2.iloc[2]

Selecting subsets of rows and columns

Mujeh df mai sai sirf name and age ka portion chahiye tha rtow 2,3 chahiye thi

In [ ]:
df.loc[[2,3]][['Name','Age']]

Conditional Selection

Ab mujeh sirf un people ka name and data chahitye jiski age 30 sai above ha

In [19]:
df2[df2["Age"] > 30]

    Name  Age    City  Salary
1  Rahul   34   Paris   70000
3  Mohan   43  Franch   85000

Ab mujeh sirf un people ka name and data chahiye jiski age 20 above ha and unki city Canada ha

In [20]:
df2[(df2["Age"] > 20) & (df2["City"] == "Canada")]

   Name  Age    City  Salary
2  Yash   29  Canada   62000

Missing Data

In [ ]:
import numpy as np
import pandas as pd

Finding missing data

In [21]:
data = {
     'A':[1,2,np.nan,4,5],
     'B':[1,2,3,4,5],
     'C':[1,2,3,np.nan,np.nan],
     'D':[1,np.nan,np.nan,np.nan,5]
}
df = pd.DataFrame(data)
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

Abhio mujeh sirf check krna ha ki value missing h yeh

In [ ]:
df.isna()

Ab mujeh check krna ha and count krna ha konsai column mai sabsai zyda missing value ha

In [ ]:
df.isna().sum()

Mujeh yeh janana ha h ki kya mere sare column mai missing value h yeh nhi

In [ ]:
df.isna().any()

Removing Missing data

In [ ]:
df

Abhi mujeh woh row show krni h sirf jismai ek bhi missing value nhi ho

In [ ]:
df.dropna()

Mujeh yhe janana h ki sirf unhi rows ko rakhna h jismai kam sai kam non missing value ho ho (NaN ke alwa )

In [ ]:
df.dropna(thresh = 3)

Filling the missing data

Ab mai jaha - jaha NaN value ha mai waha 0 fill krna h mujeh

In [ ]:
df.fillna(0)

Ab mujeh alag - alag column mai different value deni ha

In [ ]:
values = {'A':0 , 'B':100 , 'C':400 , 'D':300}
df.fillna(value=values)

Merging,Joining ,Concatenation

In [ ]:
import numpy as np
import pandas as pd

Merging 2 Dataframes

Phele hum 2 dataframe banage

In [ ]:

employees = pd.DataFrame({
      'employee_id':[1,2,3,4,5],
      'name':['Prachi','Yash','Rohit','Sohan','Mohan'],
      'department':['IT','HR','Finace','IT','HR']    
})


Salaries = pd.DataFrame({
     'employee_id': [1,2,3,6,7],
     'salary':[60000,80000,65000,70000,90000],
     'bonus':[5000,10000,7000,8000,12000]

    

    
})

In [ ]:
employees

In [ ]:
Salaries

Abhi mujeh employees and Salaries wale dataframe ko ek krna ha and mujeh sirf wahi row chahiye jo mere employee_id mai common row ho

In [ ]:
pd.merge(employees,Salaries,on = 'employee_id', how = 'inner')

Ab mujeh sare record chahiye screen per chahe match ho yeh nhi ho and missing value fill kre NaN sai

In [ ]:
pd.merge(employees,Salaries,on = 'employee_id', how = 'outer')

Kaunse employees ke salary records available hain, aur kaunse missing hain

In [ ]:
pd.merge(employees,Salaries,on = 'employee_id', how = 'left')

Ab humko pta krna h kaunsai employee ka salary record available ha and kaunsai salary records ka employee data missing ha

In [ ]:
pd.merge(employees,Salaries,on = 'employee_id', how = 'right')

2 concatination of dataframe

phele hum 2 dataframe create krege

In [22]:
df1 = pd.DataFrame({
    'A':['A0','A1','A2'],
    'B':['B0','B1','B2'],
    'C':['C0','C1','C2']    
})


df2 = pd.DataFrame({
   'A':['A3','A4','A5'],
   'B':['B3','B4','B5'],
   'C':['C3','C4','C5']

    
})

Mujeh df1 and df2 ko concat krna ha and rows ke niche rows add krna ha

In [23]:
pd.concat([df1,df2])

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

Mujeh df1 and df2 ko concat krna ha and column ke side mai columns add krna ha

In [ ]:
pd.concat([df1,df2],axis = 1)

Joining of 2 Dataframe

phele hum 2 dataframe ko create krege

In [ ]:
df1 = pd.DataFrame({
    'name':['Alice','Bob','Charlie']
},index = [1,2,3])

df2 = pd.DataFrame({
    'score':[85,90,75]
},index = [2,3,4])

In [ ]:
df1

In [ ]:
df2

Phele mujeh yeh krna ha ki df1 ke column phele aaye and df2 jke column baad mai aaye

In [ ]:
df1.join(df2)

Ab mujeh phele df2 ke column phele aaye and df1 ke baad mai aaye

In [ ]:
df2.join(df1)

Abhi mujeh sare record screen par chahiye and missing value fill ho jaye NaN sai

In [ ]:
df1.join(df2,how = 'outer')

Group By

In [ ]:
import numpy as np
import pandas as pd

Phele hum ek dataframe create karege

In [24]:
data = {
    'Category':['A','B','A','B','A','B','A','B'],
    'Store':['S1','S1','S2','S2','S1','S2','S2','S1'],
    'Sales':[100,200,150,250,120,180,200,300],
    'Quantity':[10,15,12,18,8,20,15,25],
    'Date':pd.date_range('2023-01-01',periods = 8)   
}
df = pd.DataFrame(data)
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

Mujeh group by krna h category ko and calculate the sum of Sales.

In [ ]:
d = df.groupby('Category')['Sales'].sum()
d

Mujeh group by krna h Store ko and calculate the sum of Sales.

In [ ]:
d = df.groupby('Store')['Sales'].sum()
d

mujeh multiple column ko group by krna ha like example mujeh Category and Store ko group by krna ha and calcuate the sum of Sales.

In [ ]:
d = df.groupby(['Category','Store'])['Sales'].sum()
d

Aggregation

mujeh sales ka mean nikalna ha ha sirf

In [ ]:
df['Sales'].mean()

Ab mujeh sales per he sare function use krnai ha jaise mean','median', 'count', 'max','min','sum','std'

In [ ]:
df['Sales'].agg(['mean','median', 'count', 'max','min','sum','std'])

Pivot Table

In [ ]:
import numpy as np
import pandas as pd

Phele hum ek dataframe create krege

In [25]:
data = {
    'Date':pd.date_range('2023-01-01',periods = 20),
    'Product':['A','B','C','D'] * 5,
    'Region':['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 
              'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North','South'],
    'Sales':np.random.randint(100,1000,20),
    'Units':np.random.randint(10,100,20),
    'Rep':['John','Mary','Bob','Alice','John','Mary','Bob','Alice','John','Mary',
           'Bob','Alice','John','Mary','Bob','Alice','John','Mary','Bob','Alice']
    
}
df = pd.DataFrame(data)

df['Month']= df['Date'].dt.month_name()
df['Quarter'] = 'Q' + df['Date'].dt.quarter.astype(str)
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    586     71   John  January      Q1
1  2023-01-02       B   West    536     37   Mary  January      Q1
2  2023-01-03       C  North    646     33    Bob  January      Q1
3  2023-01-04       D  South    360     89  Alice  January      Q1
4  2023-01-05       A   East    347     49   John  January      Q1
5  2023-01-06       B   West    105     96   Mary  January      Q1
6  2023-01-07       C  North    867     61    Bob  January      Q1
7  2023-01-08       D  South    130     75  Alice  January      Q1
8  2023-01-09       A   East    950     99   John  January      Q1
9  2023-01-10       B   West    635     72   Mary  January      Q1
10 2023-01-11       C  North    633     29    Bob  January      Q1
11 2023-01-12       D  South    682     36  Alice  January      Q1
12 2023-01-13       A   East    592     93   John  January      Q1
13 2023-01-14       B   West    743     16   Mary  January      Q1
14 2023-01-15       C  North    740     98    Bob  January      Q1
15 2023-01-16       D  South    953     55  Alice  January      Q1
16 2023-01-17       A   East    300     73   John  January      Q1
17 2023-01-18       B   West    181     19   Mary  January      Q1
18 2023-01-19       C  North    350     31    Bob  January      Q1
19 2023-01-20       D  South    878     38  Alice  January      Q1

Mujeh product and region ke hisab sai sales dekhnai ha and mean bhi nikalna ha Sales ka

In [ ]:
pivot1 = pd.pivot_table(df,values = "Sales",index = 'Region',columns = "Product",aggfunc = 'mean')
pivot1

mujeh product and region ke hissab sai units and sales ka average dekhna ha

In [ ]:
pivot2 = pd.pivot_table(df,values = ["Sales","Units"],index = 'Region',columns = "Product",aggfunc = 'mean')
pivot2

Cross tabs

Mujeh yeh dekna ha ki region ke hissab sai konsa product kitni bar aaya ha

In [ ]:
pd.crosstab(df['Region'],df['Product'])

Operation

In [ ]:
import numpy as np
import pandas as pd

phele hum ek dataframe create karege basic operation ke leye

DataFrame Basic Operation

In [ ]:
df1 = pd.DataFrame({
    'A':[1,2,3,4,5],
    'B':[10,20,30,40,50],
    'C':[100,200,300,400,500]
    
})
df1

mujeh pta krna h mere df1 mai kitni row and  column ha

In [ ]:
df1.shape

mujeh pta krna ha konsai column ha mere df1 mai

In [ ]:
df1.columns

mujeh yeh pta krna ha mere dataframe mai df1 mai index dtype,columns,non - null values wagera kitni ha

In [ ]:
df1.info()

mujeh yeh pta krna ha mere dataframe df1 mai kya mai statistical describe kr sakti hu columns mai

In [ ]:
df1.describe()

kya  mai kisi ek column mai kuch add kr sakti hu broadcasting ka use krke jaise mujeh 'A' column mai 10 ki add krna ha

In [ ]:
df1['A'] + 10

DataFrames Applying Functions

In [ ]:
df1

mujeh yeh krna ha 'B' column ka jo value ha usko square mai krna ha but mujeh yhe bhi krna ha mere main dataframe mai apply ho

In [ ]:
def square(x):
    return x**2

In [ ]:
df1['D'] = df1["B"].apply(square)

In [ ]:
df1